# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('add_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArtSingle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('add_time', models.IntegerField(default=0)),
                ('sort', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('picture', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DataClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('parent_id', models.IntegerField(default=0)),
                ('sort', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(db_column=b'goodsname', max_length=255)),
                ('goodstitle', models.CharField(db_column=b'goodstitle', max_length=255)),
                ('imguri', models.CharField(db_column=b'imguri', max_length=255)),
                ('created', models.IntegerField(db_column=b'created')),
                ('status', models.IntegerField(db_column=b'status')),
                ('gtype', models.IntegerField(db_column=b'type')),
                ('intro', models.CharField(db_column=b'intro', max_length=255)),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.AddField(
            model_name='data',
            name='dataclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms_app.DataClass'),
        ),
    ]
